### ISSUE TITLE
Framebuffer and TCC compiler

### ISSUE THREAD

**Issue by ArtyBiscuit** [Un1q32/sedna-mc#1]
Hello First of all, I'd like to thank for this Sendna update

I noticed that the TCC compiler was no longer available in this version, unfortunately.
is there a reason for this? and would it be possible to make it available again in the next version because this one we could compile from C and thus create our own program and flesh out what is already available.

secondly, I also noticed that there was no “/dev/fb0” or “/dev/framebuffer” file. I find this rather odd and it's a shame not to have access to it the framebuffer would allow us to have greater management of the graphics environment, which could be useful for managing specific pixels on the terminal and thus creating graphics libraries.

what is a framebuffer ? -> https://fr.wikipedia.org/wiki/Framebuffer_Linux
what can we do with ? -> https://www.youtube.com/watch?v=x1oXByIJcHU

I don't claim to have the knowledge to do it myself or even to understand exactly how it works, but if it could be added I think it would be a relevant addition.

**Comment by Un1q32** [comment]
Not sure why I didn't see this issue before, notifications are broken

**Comment by Un1q32** [comment]
TCC was removed because it was hard to use without libc headers, you can still compile C programs by using a riscv64-linux-musl toolchain on a host system, and then copying your programs over to the VM with the file import/export card.  I would like to have some kind of hard drive image you could apply to a drive, similarly to crafting a Linux drive with an 8 MB drive and a wrench, but instead of making a Linux drive it makes a drive with TCC and header files, but that would require support in the OC2 mod, and I don't know any java.

As for the framebuffer, I've not interacted with the /dev entries, but I've tested the projector and monitor and both seem to work fine.

**Comment by Un1q32** [comment]
I tested the projector again and found that /dev/fb0 does appear, but only when a monitor or projector are connected (you may have to reboot the VM after connecting one).  Since those devices are the only things that can display a framebuffer, it would be useless to have the /dev entries without them anyway.

**Comment by Un1q32** [comment]
I decided to re-add TCC in the latest release as demand was higher than expected.  I've also published libc headers, they take up about 2 MB, I recommend you put them on another drive that can be mounted at /usr/include, but you can extract them directly if your rootfs has more than 2 MB free.
